### PR TITLE
One and half auton

### PR DESCRIPTION
**Pull request by MaisieY587**

### CODE REVIEW

**Comment by Chess318** [comment]
https://github.com/frc2399/2023-Season/blob/d16aaefaacc25f1689bc72083a3d73419dece2a1/src/main/java/frc/robot/commands/auton/OneAndHalfPieceEngage.java#L39-L42
Should we be lowering the arm into position BEFORE we drive up to the piece? And also, should we be intaking as we drive up to the game piece (ie in a parallel command group)?

**Comment by edf42001** [comment]
Heeyyyyy guys, remember when I suggested 
> The line currentAngle = modAngle(currentAngle); in TurnToNAngleCmd is unnecessary because of the lines
    double error = targetAngle - currentAngle;
    error = modAngle(error);
which btw you could combine into double error = modAngle(targetAngle - currentAngle);

Turns out that broke the finish condition, because now current angle could be 360, target 0, but without modAngleing currentAngle those aren't within the range from each other :)
```java
  public boolean isFinished() {
    return PIDUtil.checkWithinRange(targetAngle, currentAngle, range);
  }
```

The *best* way to fix this is to make the `error` variable a global member variable. Then you can call
`return PIDUtil.checkWithinRange(0, error, range);` to check when the (modAngled) error is close to 0

You can test this in sim

**Comment by edf42001** [comment]
Next, I have two questions which I think you'll find very interesting:

* In sim, is the robot's starting position correct if you run two autos in a row?
* This one is extra interesting: In Sim, does the robot turn to the right angle? What about on the real robot?

Let me know if you want help investigating these!

**Comment by clocko3** [comment]
Shouldn't it go to cone up intake height too at line 42?

**Pull request closed without merging**
